[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_usd_oracle = "BZzWDRREZ3Bw4E7oJrQKVRJgkPd2hkmYLXHjpsmnUhXC"
token_minter = "7wzZRUV2jvg5fyecgdaDVXBa3eYP7yJ2KTqBCLjxPKTa"

[programs.devnet]
sol_usd_oracle = "BZzWDRREZ3Bw4E7oJrQKVRJgkPd2hkmYLXHjpsmnUhXC"
token_minter = "7wzZRUV2jvg5fyecgdaDVXBa3eYP7yJ2KTqBCLjxPKTa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "yarn run litesvm"
test = "yarn run litesvm"
